### ISSUE TITLE
How to make myself datasets？

### ISSUE THREAD

**Issue by liujun0808** [lqh12345/Jacquard_V2#1]
I want to create my own data set, which includes some 3D printed unconventional objects. How to implement it? I am a poor Chinese graduate student, please help! ：）This is my e-mail：liujun8014@163.com

**Comment by lqh12345** [comment]
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by lqh12345** [comment]
Sorry, I don't know exactly what format of dataset you want. However, if you plan to create a 2D dataset, please take photos of each object first. After taking photos, please perform data augmentation to expand the dataset. Then use software such as labelme to label each image and generate a dataset file. Finally, simply package the dataset file.
