### ISSUE TITLE
Issue about the depth information.

### ISSUE THREAD

**Issue by Zhangwenyao1** [lqh12345/Jacquard_V2#2]
Thanks for your great work!
I want to know if the depth is metric depth. And how to extract it?

**Comment by lqh12345** [comment]
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by lqh12345** [comment]
Thank you very much. 
Yes. 
You can find the relevant code in /Jacquard_V2/utils/dataset_processing/evaluation.py
# ax = fig.add_subplot(3, 2, 5)
    # plot = ax.imshow(grasp_q_img, cmap='jet', vmin=0, vmax=1)
    # ax.set_title('Q')
    # ax.axis('off')
    # plt.colorbar(plot)
    #
    # ax = fig.add_subplot(3, 2, 6)
    # plot = ax.imshow(grasp_angle_img, cmap='hsv', vmin=-np.pi / 2, vmax=np.pi / 2)
    # ax.set_title('Angle')
    # ax.axis('off')
    # plt.colorbar(plot)
