### ISSUE TITLE
数据集训练前面一些轮数的结果跟小，几乎为零

### ISSUE THREAD

**Issue by Fyzyukk** [lqh12345/Jacquard_V2#3]
作者您好，我使用您发布的这个v2版本的数据进行训练时，效果确实会有2-3%的不等提升，但是在训练的过程中前面一些轮数的loss是正常计算的，但是准确率是几乎为0或者很接近为0，到后面几十轮过后才恢复正常，请问一下这个是什么问题呢，会对准确性结果产生一些影响么，以及想了解如何能制作自己的类似Jacquard的数据集。希望您能回复我的这个问题。

**Comment by lqh12345** [comment]
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by lqh12345** [comment]
loss和准确率这个问题，请检查你的代码，应该代码有问题，我这里没有问题。
制作Jacquard数据集的问题，可以上csdn里面搜索一下，其他博主有写相关内容。

**Comment by lqh12345** [comment]
您好，您的邮件我已收到，我会尽快给您回复。
