### ISSUE TITLE
云盘中的数据集是第一版的还是第二版的？

### ISSUE THREAD

**Issue by yuqiuda** [lqh12345/Jacquard_V2#4]
作者您好，我下载了您分享的数据集，但是数据集的结构好像和readme中的不一样，您在readme中说一共四部分，但是我下载的有12个压缩包，和第一版的是一样的，我想咨询一下分享的数据集是第一版的还是第二版的？

**Comment by lqh12345** [comment]
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by lqh12345** [comment]
您好，我上传到百度网盘和微软云盘的是jacquard v2数据集。
使用时，解压所有的压缩包，你会得到JacquardV2_Dateset_0~JacquardV2_Dateset_11（共十二个文件夹），这十二文件夹共同组成jacquard v2数据集。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月12日(周六) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lqh12345/Jacquard_V2] 云盘中的数据集是第一版的还是第二版的？ (Issue #4)




 
作者您好，我下载了您分享的数据集，但是数据集的结构好像和readme中的不一样，您在readme中说一共四部分，但是我下载的有12个压缩包，和第一版的是一样的，我想咨询一下分享的数据集是第一版的还是第二版的？

**Comment by yuqiuda** [comment]
> 您好，我上传到百度网盘和微软云盘的是jacquard v2数据集。 使用时，解压所有的压缩包，你会得到JacquardV2_Dateset_0~JacquardV2_Dateset_11（共十二个文件夹），这十二文件夹共同组成jacquard v2数据集。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月12日(周六) 晚上9:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [lqh12345/Jacquard_V2] 云盘中的数据集是第一版的还是第二版的？ (Issue #4) 作者您好，我下载了您分享的数据集，但是数据集的结构好像和readme中的不一样，您在readme中说一共四部分，但是我下载的有12个压缩包，和第一版的是一样的，我想咨询一下分享的数据集是第一版的还是第二版的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢您的回复，我解压的数据集和您说的有些出入，解压后不是JacquardV2_Dateset_0，而是Jacquard_Dateset_0，没有V2，不知道有没有问题，想跟您确认一下。截图如下。感谢！
![image](https://github.com/user-attachments/assets/c0624d0a-e8e8-4eec-8da0-f6808aee437d)

**Comment by lqh12345** [comment]
正确的，没有问题。

**Comment by yuqiuda** [comment]
> 正确的，没有问题。

谢谢，非常感谢。
